### PR TITLE
feat(bd-programs): added github actions to test bd programs

### PR DESCRIPTION
**Pull request by andresmgsl**
I`ll let this here for now, but later I wanna discuss it with you before merging to master @danmt

### CODE REVIEW

**Comment by andresmgsl** [comment]
I think would be neccesary to add some 'path specification' in the GH Action yaml file to run it only when bulldozer-programs files change. No need to run the test if the README.md or some other not related file change.

**Comment by andresmgsl** [comment]
Hey brou @danmt , i just finished refacting the github actions yaml file, using `nx affected' command as you suggested, plus I  added a validation to install Anchor an all its dependencies only if necessary. I think all is working fine, but we have a problem when building the 'Bulldozer-client' app, it fail due to the bundle size exceed the default angular limit. I think we should review and fix all test before merging this. Let me know what u think.

**Comment by danmt** [comment]
Hey @andresmgsl, if you change [budget from 1mb to 2mb](https://github.com/heavy-duty/platform/blob/andresmgsl/test-programs-github-actions/workspace.json#L714) the problem should be solved.

**Comment by danmt** [comment]
The action looks pretty nice. I wonder if there's an easier way to tell if `bulldozer-programs` is affected. Maybe nx has a CLI command for that. I'll look around.

**Pull request merged**
